name: Deploy to RunPod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to RunPod
        uses: runpod/runpod-cloud@v1
        with:
          api-key: ${{ secrets.RUNPOD_API_KEY }}
          template: runpod.yaml
          wait-for-deployment: true
          env:
            RUNPOD_URL: ${{ secrets.RUNPOD_URL }}
            HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
            TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
            TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
            TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }} 